export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_UNAUTHENTICATED = 'USER_UNAUTHENTICATED';
export const AUTHENTICATION_ERROR  = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const USER_EXISTS = 'USER_EXISTS';
export const CHECK_USER_ERROR ='CHECK_USER_ERROR';
export const USER_NAME_FREE = 'USER_NAME_FREE';
export const USER_REGISTERED = 'USER_REGISTERED';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING'; 
    